export const CHANGE_FORM = "CHANGE_FORM"
export const CUT_SCHEDULE = "CUT_SCHEDULE"
export const INIT = "INIT"
export const SET_DEFAULT = "SET_DEFAULT"
export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE"
